import "@/components/sass/globals.scss";

import { Fragment } from "react";

import dynamic from "next/dynamic";

const Header = dynamic(() => import("@/components/ui/header/Header"));

const Footer = dynamic(() => import("@/components/ui/footer/Footer"));

export const metadata = {
  title: "Govokasi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Fragment>
          <main>
            <Header />
            {children}
            <Footer />
          </main>
        </Fragment>
      </body>
    </html>
  );
}
